version: "3.7"
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: keycloak_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: keycloak
    container_name: keycloak
    ports:
      - "11080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
    depends_on:
      - postgres



